### ISSUE TITLE
Empty string is saved as a space when using put_item

### ISSUE THREAD

**Issue by froy001** [ex-aws/ex_aws_dynamo#21] opened 2020-07-02 14:15 UTC
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

* Elixir & Erlang versions (elixir --version):
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.2 (compiled with Erlang/OTP 21)

* ExAws version `mix deps |grep ex_aws`
ex_aws 2.1.3 (Hex package) (mix)
  locked at 2.1.3 (ex_aws) 0bdbe2ae

* HTTP client version. IE for hackney do `mix deps | grep hackney`
hackney 1.16.0 (Hex package) (rebar3)`

### Current behavior
I have an item that looks like this:
content = %{ key1: "", key2: "some value", key3: "some other value", key4: "" }
Dynamo.put_item(table_name, remove_nil_keys(content)) |> ExAws.request!()

remove_nil_keys/1 only removes nil keys. nothing else. 

When I open the item in DynamoDb I find:
key1: " "
key2: some value
key3: some other value
key4: " " 

**i.e. the empty string became a space.**

Include code samples, errors and stacktraces if appropriate.

### Expected behavior
the DynamoDb Item should look like this:
key1: `<empty>`
key2: some value
key3: some other value
key4: `<empty>`

**Comment by darrenklein** [comment] 2020-07-02 14:36
Thanks very much for reporting this issue. I'll try to look into it as soon as I can.

**Comment by darrenklein** [comment] 2020-07-03 13:27
@froy001 Where do you have `remove_nil_keys` defined? It doesn't appear to be a part of `ex_aws_dynamo` or its dependencies.

**Comment by froy001** [comment] 2020-07-03 13:44
> @froy001 Where do you have `remove_nil_keys` defined? It doesn't appear to be a part of `ex_aws_dynamo` or its dependencies.

it's just a helper function I wrote that removes nil k\v pairs from the content map. It is not related to the ex_aws_dynamo in any way. I mentioned it because its part of my code and I wanted you to know that. The bug is present with or without using it.

**Comment by darrenklein** [comment] 2020-07-03 13:49
Ah ok, I see, thanks for clarifying.

**Comment by darrenklein** [comment] 2020-07-03 14:10
I'm not able to replicate this bug - I modified one of the tests so that a value is an empty string, but the returned data has that data correctly set as `nil`. In this case, I've changed `age` from `23` to `""`:

```
test "put and get item with map values work" do
  {:ok, _} = Dynamo.create_table(Test.User, :email, [email: :string], 1, 1) |> ExAws.request()

  user = %Test.User{
    email: "foo@bar.com",
    name: %{first: "bob", last: "bubba"},
    age: "",
    admin: false
  }

  assert {:ok, _} = Dynamo.put_item(Test.User, user) |> ExAws.request()

  item =
    Test.User
    |> Dynamo.get_item(%{email: user.email})
    |> ExAws.request!()
    |> Dynamo.decode_item(as: Test.User)

  assert user == item
end
```

the test fails with the message:

```
  1) test put and get item with map values work (ExAws.DynamoIntegrationTest)
     test/lib/dynamo/integration_test.exs:55
     Assertion with == failed
     code:  assert user == item
     left:  %Test.User{admin: false, age: "", email: "foo@bar.com", name: %{first: "bob", last: "bubba"}}
     right: %Test.User{admin: false, age: nil, email: "foo@bar.com", name: %{first: "bob", last: "bubba"}}
     stacktrace:
       test/lib/dynamo/integration_test.exs:73: (test)
```

which is what I'd expect to happen. On the left side, we see `age: ""`, on the right side, we see `age: nil`.

Could I ask you to provide your definition for `remove_nil_keys/1` so we can get a complete picture of what may be happening here?

**Comment by froy001** [comment] 2020-07-03 14:29
Sure here it is.
```
 defp remove_nil_keys(%{} = content) do
    :maps.filter(fn _, v -> v != nil end, content)
  end

```
I am not sure how the decoding should work, I would say that an empty string should be an empty string not nil. 
But I am not talking about the decoding. I am talking about how the key is saved in DynamoDb. When using AWS SDK (JAVA and Js) when putting an item with a key that has a value "" you get `<empty>` in the dynamodb table. While when putting an item using ex_aws_dynamo with a key = "" I get " " inside DynamoDb on AWS. 
It so happens that I need the `<empty>` value in the dynamodb item. And ex_aws_dynamo is not doing that, it somehow saves a non-empty string as the attribute value.

**Comment by darrenklein** [comment] 2020-07-03 16:15
Regarding the encoding/decoding - until recently, DDB did not support empty string values, it would raise an error `'An AttributeValue may not contain an empty string'` - however, that seems to have changed a few months back - [announcement](https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/?sc_channel=sm&sc_campaign=DB_Blog&sc_publisher=TWITTER&sc_country=DynamoDB&sc_geo=GLOBAL&sc_outcome=awareness&trk=ddbemptyvalues_051820_TWITTER&sc_category=Amazon%20DynamoDB&linkId=88894636). So yeah, this project should probably support that, though I understand this is not the focal point of the issue you're posting about, I'll add that as a separate issue so I (or someone) can get around to it later.

Anyway, I updated my local DDB instance to the latest version, 1.13.1, which adds support for empty values.

Regardless, my bad about leaving the decoder step in before, of course that could obscure things a bit. However, I removed the decoder step, `|> Dynamo.decode_item(as: Test.User)`, but the pre-decoded data also seems to affirm what's expected -

```
  1) test put and get item with map values work (ExAws.DynamoIntegrationTest)
     test/lib/dynamo/integration_test.exs:55
     Assertion with == failed
     code:  assert user == item
     left:  %Test.User{admin: false, age: "", email: "foo@bar.com", name: %{first: "bob", last: "bubba"}}
     right: %{"Item" => %{"admin" => %{"BOOL" => false}, "email" => %{"S" => "foo@bar.com"}, "name" => %{"M" => %{"first" => %{"S" => "bob"}, "last" => %{"S" => "bubba"}}}}}
     stacktrace:
       test/lib/dynamo/integration_test.exs:73: (test)
```

You'll see that, on the right side, `age` was not written to the record at all (the decoder was adding that back in as `nil` after the data was retrieved`) - this is the result of `age` getting stripped off during the encoding process, see `do_encode/1` in encodable.ex (I've added the comment here):

```
  def do_encode(map) do
    Enum.reduce(map, %{}, fn
      # this case results in the empty string value being excluded from the record that is being sent to DDB
      {_, ""}, map ->
        map

      {k, v}, map when is_binary(k) ->
        Map.put(map, k, ExAws.Dynamo.Encodable.encode(v, []))

      {k, v}, map ->
        key = String.Chars.to_string(k)
        Map.put(map, key, ExAws.Dynamo.Encodable.encode(v, []))
    end)
  end
```

So that empty string shouldn't be making it to the database at all, let alone be written as `" "`.

Just to see what would happen, I swapped that case out for

```
      {k, ""}, map ->
        Map.put(map, k, ExAws.Dynamo.Encodable.encode("", []))
```

and here we do see `age` come back as an empty string `""`, but still not `" "`:

```
  2) test put and get item with map values work (ExAws.DynamoIntegrationTest)
     test/lib/dynamo/integration_test.exs:55
     Assertion with == failed
     code:  assert user == item
     left:  %Test.User{admin: false, age: "", email: "foo@bar.com", name: %{first: "bob", last: "bubba"}}
     right: %{
              "Item" => %{"admin" => %{"BOOL" => false}, "age" => %{"S" => ""}, "email" => %{"S" => "foo@bar.com"}, "name" => %{"M" => %{"first" => %{"S" => "bob"}, "last" => %{"S" => "bubba"}}}}
            }
     stacktrace:
       test/lib/dynamo/integration_test.exs:73: (test)
```

As far as I can tell, this issue is not being caused by ex_aws_dynamo... the current behavior will completely remove any key/values from the record where the value is an empty string during the encoding process, and decode any such record as having a `nil` value when retrieving that record.

**Comment by darrenklein** [comment] 2020-07-06 01:03
@froy001 Any progress on this issue?  The new major version release of this app (v4.0.0) supports the new DDB behavior of allowing empty strings to be written to the DB. You might give that a try and see if it helps, though I think that the problem you're encountering is not related to ExAws.Dynamo.

**Comment by darrenklein** [comment] 2020-07-13 21:51
I am unable to replicate this issue and I don't think that it is caused by ExAws.Dynamo, so I'm closing it for now. Please re-open it if you are able to confirm that it is caused by ExAws.Dynamo.

Thanks again for your support of this project, and best of luck getting this worked out!

**Closed by darrenklein** 2020-07-13 21:51 UTC
